name: Rest Assured Tests

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Make Maven Wrapper
        run: chmod +x ./mvnw

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build the project
        run: ./mvnw clean install -B

      - name: Run tests
        run: ./mvnw test -B

      - name: Generate Surefire HTML Report
        run: ./mvnw surefire-report:report-only

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-html-report
          path: target/site/surefire-report.html

      - name: Upload XML Test Results
        uses: actions/upload-artifact@v4
        with:
          name: surefire-xml-report
          path: target/surefire-reports/